### ISSUE TITLE
package.json version should update to 0.2.2

### ISSUE THREAD

**Issue by favoyang** [kongregate/asset-bundle-builder#8]
Git tag: 0.2.2 
package.json 0.2.1

**Comment by randomPoison** [comment]
Ah, good catch! I've updated the `package.json` and remade the v0.2.2 tag, hopefully that fixes the OpenUPM build 🤞

**Comment by randomPoison** [comment]
Looks good now, thanks for the help!

**Comment by favoyang** [comment]
Yes, retag will trigger failed build to rerun. Looks good now.
